import type { Metadata } from "next";
import { Navbar } from "../interfaces/components/navbar";
import { Sora } from 'next/font/google';
import './globals.css';
import { TestResultsProvider } from "../interfaces/contexts/TestResultsContext";

const sora = Sora({
  weight: ['400', '600', '700'],
  style: 'normal',

})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={sora.className}>
      <body>
        <TestResultsProvider>
          <Navbar />
          {children}
        </TestResultsProvider>
      </body>
    </html>
  );
}
